FROM microsoft/dotnet:2.2-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY AppContainer.csproj AppContainer/
RUN dotnet restore AppContainer/AppContainer.csproj
COPY . .
WORKDIR /src/AppContainer
RUN dotnet build AppContainer.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish AppContainer.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "AppContainer.dll"]