FROM microsoft/dotnet:2.2-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY aciContainer.csproj aciContainer/
RUN dotnet restore aciContainer/aciContainer.csproj
COPY . .
WORKDIR /src/aciContainer
RUN dotnet build aciContainer.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish aciContainer.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "aciContainer.dll"]